### ISSUE TITLE
Zenodo  API

### ISSUE THREAD

**Issue by hrzepa** [ImperialCollegeLondon/champ#54]
Chris,

This is the current response from  Zendo to their API  mapping. 

So a typical entry  (DOI: 10.14469/HPC/8712 ) would map

subjectScheme="Gibbs_Energy"  maps to **scheme**
-1329.320538  maps to  **subject**

In future 

valueURI="http://gaussian.com/thermo/" will instead map to identifier  and
subject will map to subject (a change!) 

There is no mention of how eg 

schemeURI="https://doi.org/10.1351/goldbook.G02629"  maps
and  I have queried this with them.

also 

https://zenodo.org/record/18632/export/dcite4  would map to eg their assigned  DOI as per 10.5281/zenodo.18632 in order to check the mappings.

Can you try an initial Zenodo implementation using eg these mappings so that we can iterate to an answer.

**The current portal will have to be modified so that any entry must be capable of multiple publications.  At the moment, once published, no further publications are possible.**

**Comment by cc-a** [comment]
So I don't think this gets us any further unfortunately. As far as I can tell the API only allows controlled values for scheme based on the value of identifier (their documentation is not great here). It doesn't seem to be possible to provide "Gibbs_energy" as the value for scheme. A value for identifier must also be provided.

**Comment by cc-a** [comment]
I'll open a separate issue for the multiple publications.

**Comment by hrzepa** [comment]
Chris,

So can we try for the  "near future",  where 

subject matches the value of the subject, ie -412.777622 or whatever
scheme has the value Gibbs_Energy
and identifier has the value (valueURI) of http://gaussian.com/thermo/

(will http://gaussian.com/thermo/ <http://gaussian.com/thermo/> be replaced simply by the value  "URL" ?  And is the scheme value  "Gibbs_Energy" simply rejected? Only an experiment can tell)

The "missing" attribute would be schemeURI which would have had the value  https://doi.org/10.1351/goldbook.G02629 <https://doi.org/10.1351/goldbook.G02629> 

At the moment then the best we can do is to make SchemeURI  and ValueURI have the same value, which is not optimal but better than nothing

Can we do the experiment, and then send the results back to Zenodo for clarification/correction/implementation? 

> As for the road map I cannot really confirm a date, but in the near future the subjects field will contain:
> - "identifier" matching to "valueURI"
> - "subject" matching to "subject"
> - "scheme" matching to "subjectScheme"
>

**Comment by hrzepa** [comment]
Chris,


PS My reference page is at  https://www.ch.ic.ac.uk/rzepa/talks/FAIR20/data-metadata3.html <https://www.ch.ic.ac.uk/rzepa/talks/FAIR20/data-metadata3.html>

There again we must apparently map  schemeURI  to  valueURI  and use eg http://www.inchi-trust.org/

**Comment by cc-a** [comment]
No dice. The scheme value of "Gibbs_Energy" is rejected. For Zenodo that field has a limitied  vocabulary based on the value of the identifier field i.e. if identifier is a URL then the value of scheme must be "url"

**Comment by hrzepa** [comment]
I will contact zenodo to see if their mods which might allow this could be expedited 

Henry Rzepa
