### ISSUE TITLE
Jobs showing as completed but stopping mid flow?

### ISSUE THREAD

**Issue by hrzepa** [ImperialCollegeLondon/champ#68]
A lot of jobs show as completed, but with truncated outputs and no obvious errors (three today).  This is starting to get really bad now, with ~50% of jobs ending this way (jobs  326, 325, 323 etc.

The trouble is that the user  is getting absolutely no information on what is causing these problems? 
![Screenshot 918](https://user-images.githubusercontent.com/7828928/136827191-63402857-8cf0-45dd-ab2c-dbbc74e7dc97.jpg)

**Comment by cc-a** [comment]
This was tracked down as a system problem with running Gaussian jobs, unrelated to the CHAMP.
